export { default as Menu } from "./HeaderUser";
export { default as CartSlide } from "./CartSlide";
export { default as Footer } from "./Footer";
export { default as Button } from "./Button";
export { default as CartIcon } from "./CartIcon";
export { default as Input } from './Input'
export { default as Span } from './Span'
export { default as Vehicle } from './Vehicle'
export { default as Title } from './Title'
export { default as ItemSlide } from './ItemSlide'
export { default as SEO } from './SEO/index'
export { default as settings } from './settings/settings-Development'
export { default as ProductModal } from './productModal'
export { default as SelectCustom } from './Select'
